version: "3.9"

services:


  alert:
    build:
      context: ./alert
      dockerfile: Dockerfile
    container_name: uptimeguard-alert 
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis   



  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: uptimeguard-db
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis


  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    container_name: uptimeguard-engine
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis  


  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: uptimeguard-worker
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis  

  redis:
    image: redis:7
    container_name: uptimeguard-redis
    ports:
      - "6379:6379"
    restart: always